#!/usr/bin/env bash
set -euo pipefail

file="src/ui.js"
mod="src/module.json"

rg -q "import \{ shouldFilterMessage, decodeDelta \} from '/data/UserData/move-anything/shared/input_filter.mjs';" "$file"
rg -q "import \{ openTextEntry, closeTextEntry, isTextEntryActive, handleTextEntryMidi, drawTextEntry, tickTextEntry \} from '/data/UserData/move-anything/shared/text_entry.mjs';" "$file"
rg -q "const KNOB_CC_START = 71;" "$file"
rg -q "const KNOB_CC_END = 78;" "$file"
rg -q "const KNOB_BINDINGS = \\[" "$file"
rg -q "key: 'root', label: 'Root'" "$file"
rg -q "key: 'chord_type', label: 'Type'" "$file"
rg -q "key: 'inversion', label: 'Inversion'" "$file"
rg -q "key: 'bass', label: 'Bass'" "$file"
rg -q "key: 'pad_octave', label: 'Pad Oct'" "$file"
rg -q "key: 'strum', label: 'Strum'" "$file"
rg -q "key: 'strum_dir', label: 'Str Dir'" "$file"
rg -q "key: 'articulation', label: 'Art'" "$file"
rg -q "function noteToPad\(" "$file"
rg -q "const PAD_NOTE_MIN = 36;" "$file"
rg -q "const PAD_NOTE_MAX = 67;" "$file"
rg -q "const PAD_NOTE_FALLBACK_MIN = 68;" "$file"
rg -q "const PAD_NOTE_FALLBACK_MAX = 99;" "$file"
rg -q "const delta = decodeDelta\(d2\);" "$file"
rg -q "global_octave" "$file"
rg -q "global_transpose" "$file"
rg -q "pad_octave" "$file"
rg -q "const EDIT_KEYS   = \\['pad','root','chord_type','inversion','bass','pad_octave','strum','strum_dir','articulation','reverse_art','global_octave','global_transpose','bank','reset_patch','save'\\]" "$file"
rg -q "bass:         \\['none','c','c#','d','d#','e','f','f#','g','g#','a','a#','b'\\]" "$file"
rg -q "'maj7sus2'" "$file"
rg -q "'maj9no3'" "$file"
rg -q "'13b9'" "$file"
rg -q "'m6addb13'" "$file"
rg -q "if \\(key === 'bass'\\) return raw === 'none' \\? raw : raw.toUpperCase\\(\\);" "$file"
rg -q "if \\(key === 'bank'\\)" "$file"
rg -q "let editValueMode = false;" "$file"
rg -q "const isTranspose = key === 'global_transpose';" "$file"
rg -q "Global Trans" "$file"
rg -q "if \\(key === 'root'\\) return raw.toUpperCase\\(\\);" "$file"
rg -q "function triggerSave\(" "$file"
rg -q "const activePresetName = dspGet\\('preset_name'\\) \\|\\| '';" "$file"
rg -q "if \\(presetName !== activePresetName\\) \\{" "$file"
rg -q "dspSet\\('preset', presetIndex\\);" "$file"
rg -q "if \\(editValueMode\\) \\{" "$file"
rg -Fq "editRow = clamp(editRow + delta, 0, EDIT_KEYS.length - 1);" "$file"
rg -q "if \\(key === 'save'\\) \\{" "$file"
rg -q "if \\(key === 'reset_patch'\\) \\{" "$file"
rg -q "function triggerResetPatch\\(" "$file"
rg -q "function handleKnobTurn\\(cc, value\\) \\{" "$file"
rg -q "function drawKnobOverlay\\(\\) \\{" "$file"
rg -q "if \\(status === 0xB0 && d1 >= KNOB_CC_START && d1 <= KNOB_CC_END\\) \\{" "$file"
rg -q "resetStatus = 'confirm';" "$file"
rg -q "editValueMode = true;" "$file"
rg -q "editValueMode = false;" "$file"
rg -q "Clk:edit" "$file"
rg -q "Clk:done" "$file"
rg -q "openTextEntry\\(\\{" "$file"
rg -q "title: 'Save Preset'" "$file"
rg -q "dspSet\\('save', nameToSave\\);" "$file"
rg -q "closeTextEntry" "$file"
rg -q "if \\(isTextEntryActive\\(\\)\\) \\{" "$file"
rg -q "closeTextEntry\\(\\);" "$file"
rg -q "if \\(isTextEntryActive\\(\\)\\) \\{" "$file"
rg -q "handleTextEntryMidi\\(data\\);" "$file"
rg -q "\"chain_params\"" "$mod"
if rg -q "\"ui_hierarchy\"" "$mod"; then
  echo "FAIL: ui_hierarchy must stay disabled so custom preset browser UI remains active"
  exit 1
fi
